name: Tests

on:
  workflow_dispatch:
    branches:
      - '*'
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  e2e-test:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.triggering_branch == 'test')
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ github.sha }}

      - name: Print debug message
        shell: bash
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "github.ref=${{ github.ref }}"
          echo "github.sha=${{ github.ref }}"