name: build
on:
  push:
    branches:
      - '**'
  #pull_request:
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'build all'
        required: false
        default: false
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'master' }}

jobs:
  compile:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-tags: true
      - name: Print debug message
        shell: bash
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "GITHUB_REF=${GITHUB_REF}"